### ISSUE TITLE
AP doesn't start "Traceback iin  Start_PumpAP thread.start()"

### ISSUE THREAD

**Issue by biejay** [P0cL4bs/WiFi-Pumpkin-deprecated#103]
The Ap doesnt start completely. It gets me some error messages:

`Loading debugging mode

[_] Current Session::ID [NjIzMDU=]
[*] Configuring hostapd...
[_] enable forwarding in iptables...
[_] Configuring dhcpd...
[_] Sharing Internet Connections with NAT...
Traceback (most recent call last):
  File "/usr/share/WiFi-Pumpkin/core/main.py", line 1219, in Start_PumpAP
    thread.start()
  File "/usr/share/WiFi-Pumpkin/core/utility/threads.py", line 198, in start
    self.makeLogger()
  File "/usr/share/WiFi-Pumpkin/core/utility/threads.py", line 206, in makeLogger
    setup_logger('hostapd', './logs/AccessPoint/hostapd.log',self.session)
  File "/usr/share/WiFi-Pumpkin/core/utils.py", line 90, in setup_logger
    fileHandler = logging.FileHandler(log_file, mode='a')
  File "/usr/lib/python2.7/logging/**init**.py", line 913, in **init**
    StreamHandler.**init**(self, self._open())
  File "/usr/lib/python2.7/logging/__init__.py", line 943, in _open
    stream = open(self.baseFilename, self.mode)
IOError: [Errno 2] Datei oder Verzeichnis nicht gefunden: '/usr/share/WiFi-Pumpkin/logs/AccessPoint/hostapd.log'`
#### Please tell us details about your environment.
- Card wireless adapters name (please check if support AP/mode): TP-Link TL-WN722N
- Version used tool: 0.8.3
- Virtual Machine (yes or no and which): yes, VMWare Fusion on MacBook
- Operating System and version: Kali Linux 2.0

**Comment by mh4x0f** [comment]
#102 solution in progress...
