### ISSUE TITLE
Problem with installation

### ISSUE THREAD

**Issue by jaguarmoves** [P0cL4bs/WiFi-Pumpkin-deprecated#148]
## What's the problem (or question)?
dont mined the "bla bla" its a very long code cannot paste it..
In the installation i got this error :  

Failed building wheel for pillow
bla .. bla ..bla bla..
bla .. bla ..bla bla..
bla .. bla ..bla bla..
bla .. bla ..bla bla..
bla .. bla ..bla bla..
bla .. bla ..bla bla..
bla .. bla ..bla bla..

Failed building wheel for cryptography
bla .. bla ..bla bla..
bla .. bla ..bla bla..
bla .. bla ..bla bla..
bla .. bla ..bla bla..
bla .. bla ..bla bla..

Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-w_pZqB/Pillow/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-Da8oAx-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-w_pZqB/Pillow/
----------------------------------------
[=] checking dependencies  
----[✔]----[+] hostapd Installed
----------------------------------------
[+] Distribution Name: Kali
----------------------------------------
[=]  Install WiFi-Pumpkin 
[✔] binary::/usr/bin/
[✔] wifi-pumpkin installed with success
[✔] execute  sudo wifi-pumpkin in terminal
[+] P0cL4bs Team CopyRight 2015-2016
[+] Enjoy

root@Jagmov:~/Desktop/WiFi-Pumpkin# ./wifi-pumpkin
Traceback (most recent call last):
  File "wifi-pumpkin.py", line 50, in <module>
    from core.main import Initialize
  File "/usr/share/WiFi-Pumpkin/core/main.py", line 31, in <module>
    from core.widgets.tabmodels import (
  File "/usr/share/WiFi-Pumpkin/core/widgets/tabmodels.py", line 7, in <module>
    from core.utility.threads import ThreadPopen
  File "/usr/share/WiFi-Pumpkin/core/utility/threads.py", line 19, in <module>
    from core.servers.proxy.controller.handler import MasterHandler
  File "/usr/share/WiFi-Pumpkin/core/servers/proxy/controller/handler.py", line 1, in <module>
    from plugins.extension import *
  File "/usr/share/WiFi-Pumpkin/plugins/extension/replaceImages.py", line 3, in <module>
    from mitmproxy.models import decoded
ImportError: No module named mitmproxy.models

*answer here*
i dont know

#### Please tell us details about your environment.
* Card wireless adapters name (please check if support AP/mode):
ralink3070 
* Version used tool: 
WiFi-Pumpkin v0.8.4
* Virtual Machine (yes or no and which): 
yes vmware : guest host kali linux light latest
* Operating System and version: 
host : windows 10 .../// guest host : kali linux light latest

**Comment by jaguarmoves** [comment]
nvm after long process installing the mitm i finally solved it

**Comment by jaguarmoves** [comment]
nvm it  after long process installing the mitm depedencies i finally solved it.
