### ISSUE TITLE
ubuntu after insalling this is what i got plz help me

### ISSUE THREAD

**Issue by koki1010** [P0cL4bs/WiFi-Pumpkin-deprecated#15]
WARNING: No route found for IPv6 destination :: (no default route?)
Traceback (most recent call last):
  File "/usr/share/WiFi-Pumpkin/wifi-pumpkin.py", line 5, in <module>
    from Core.Main import Initialize
  File "/usr/share/WiFi-Pumpkin/Core/Main.py", line 3, in <module>
    import Modules as pkg
  File "/usr/share/WiFi-Pumpkin/Modules/**init**.py", line 7, in <module>
    module = loader.find_module(name).load_module(name)
  File "/usr/lib/python2.7/pkgutil.py", line 246, in load_module
    mod = imp.load_module(fullname, self.file, self.filename, self.etc)
  File "/usr/share/WiFi-Pumpkin/Modules/monitors/**init**.py", line 7, in <module>
    module = loader.find_module(name).load_module(name)
  File "/usr/lib/python2.7/pkgutil.py", line 246, in load_module
    mod = imp.load_module(fullname, self.file, self.filename, self.etc)
  File "/usr/share/WiFi-Pumpkin/Modules/monitors/Credentials.py", line 2, in <module>
    from Core.loaders.Stealth.PackagesUI import *
  File "/usr/share/WiFi-Pumpkin/Core/loaders/Stealth/PackagesUI.py", line 6, in <module>
    from Modules.servers.PhishingManager import frm_PhishingManager
  File "/usr/share/WiFi-Pumpkin/Modules/servers/**init**.py", line 7, in <module>
    module = loader.find_module(name).load_module(name)
  File "/usr/lib/python2.7/pkgutil.py", line 246, in load_module
    mod = imp.load_module(fullname, self.file, self.filename, self.etc)
  File "/usr/share/WiFi-Pumpkin/Modules/servers/PhishingManager.py", line 5, in <module>
    from BeautifulSoup import BeautifulSoup
ImportError: No module named BeautifulSoup

**Comment by mh4x0f** [comment]
``` sh
$ sudo pip install BeautifulSoup
```

**Comment by koki1010** [comment]
Traceback (most recent call last):
  File "/usr/share/WiFi-Pumpkin/wifi-pumpkin.py", line 5, in <module>
    from Core.Main import Initialize
  File "/usr/share/WiFi-Pumpkin/Core/Main.py", line 14, in <module>
    from isc_dhcp_leases.iscdhcpleases import IscDhcpLeases
ImportError:

**Comment by koki1010** [comment]
WARNING: No route found for IPv6 destination :: (no default route?)
Traceback (most recent call last):
  File "/usr/share/WiFi-Pumpkin/wifi-pumpkin.py", line 5, in <module>
    from Core.Main import Initialize
  File "/usr/share/WiFi-Pumpkin/Core/Main.py", line 14, in <module>
    from isc_dhcp_leases.iscdhcpleases import IscDhcpLeases
ImportError: No module named isc_dhcp_leases.iscdhcpleases

**Comment by koki1010** [comment]
i install dhcp

**Comment by koki1010** [comment]
WARNING: No route found for IPv6 destination :: (no default route?)
Traceback (most recent call last):
  File "/usr/share/WiFi-Pumpkin/wifi-pumpkin.py", line 5, in <module>
    from Core.Main import Initialize
  File "/usr/share/WiFi-Pumpkin/Core/Main.py", line 16, in <module>
    from Core.helpers.update import frm_githubUpdate
  File "/usr/share/WiFi-Pumpkin/Core/helpers/update.py", line 4, in <module>
    from Core.loaders.master.github import GithubUpdate,UrllibDownload
  File "/usr/share/WiFi-Pumpkin/Core/loaders/master/github.py", line 1, in <module>
    from config import Config
ImportError: No module named config
