### ISSUE TITLE
cat not install in kali 2.0

### ISSUE THREAD

**Issue by darkr4y** [P0cL4bs/WiFi-Pumpkin-deprecated#152]
download the 0.8.4 deb and use gdebi to install it.
```
 $ cat /etc/issue
Kali GNU/Linux Rolling \n \l

 $ uname -a 
Linux DarKali 4.8.0-kali2-686-pae #1 SMP Debian 4.8.15-1kali1 (2016-12-23) i686 GNU/Linux
```
when in the step of pip's installing,it return some error:

```
...

build/temp.linux-i686-2.7/_openssl.c:70043:18: note: (near initialization for ‘_cffi_struct_unions[131].alignment’)
    build/temp.linux-i686-2.7/_openssl.c:70047:12: error: invalid application of ‘sizeof’ to incomplete type ‘X509_STORE_CTX {aka struct x509_store_ctx_st}’
         sizeof(X509_STORE_CTX), offsetof(struct _cffi_align__X509_STORE_CTX, y), 126, 10 },
                ^~~~~~~~~~~~~~
    build/temp.linux-i686-2.7/_openssl.c:70047:5: error: initializer element is not constant
         sizeof(X509_STORE_CTX), offsetof(struct _cffi_align__X509_STORE_CTX, y), 126, 10 },
         ^~~~~~
    build/temp.linux-i686-2.7/_openssl.c:70047:5: note: (near initialization for ‘_cffi_struct_unions[133].size’)
    In file included from /usr/include/sched.h:28:0,
                     from /usr/include/pthread.h:23,
                     from /usr/include/openssl/crypto.h:406,
                     from /usr/include/openssl/bio.h:20,
                     from /usr/include/openssl/asn1.h:16,
                     from build/temp.linux-i686-2.7/_openssl.c:450:
    build/temp.linux-i686-2.7/_openssl.c:70047:29: error: initializer element is not constant
         sizeof(X509_STORE_CTX), offsetof(struct _cffi_align__X509_STORE_CTX, y), 126, 10 },
                                 ^
    build/temp.linux-i686-2.7/_openssl.c:70047:29: note: (near initialization for ‘_cffi_struct_unions[133].alignment’)
    error: command 'i686-linux-gnu-gcc' failed with exit status 1
    
    ----------------------------------------
  Rolling back uninstall of cryptography

...
```
and run the wifi-pumpkin, it returns:

```
 $ wifi-pumpkin 
Traceback (most recent call last):
  File "wifi-pumpkin.py", line 50, in <module>
    from core.main import Initialize
  File "/usr/share/WiFi-Pumpkin/core/main.py", line 31, in <module>
    from core.widgets.tabmodels import (
  File "/usr/share/WiFi-Pumpkin/core/widgets/tabmodels.py", line 7, in <module>
    from core.utility.threads import ThreadPopen
  File "/usr/share/WiFi-Pumpkin/core/utility/threads.py", line 19, in <module>
    from core.servers.proxy.controller.handler import MasterHandler
  File "/usr/share/WiFi-Pumpkin/core/servers/proxy/controller/handler.py", line 1, in <module>
    from plugins.extension import *
  File "/usr/share/WiFi-Pumpkin/plugins/extension/html_inject.py", line 2, in <module>
    from bs4 import BeautifulSoup
  File "/usr/local/lib/python2.7/dist-packages/bs4/__init__.py", line 30, in <module>
    from .builder import builder_registry, ParserRejectedMarkup
  File "/usr/local/lib/python2.7/dist-packages/bs4/builder/__init__.py", line 311, in <module>
    from . import _html5lib
  File "/usr/local/lib/python2.7/dist-packages/bs4/builder/_html5lib.py", line 57, in <module>
    class TreeBuilderForHtml5lib(html5lib.treebuilders._base.TreeBuilder):
AttributeError: 'module' object has no attribute '_base'

```
seems the cryptography's compile error.. but when run wifi-pumpkin it seems a bs4's error?
how to resolve?

**Comment by darkr4y** [comment]
OK its a html5lib issue:
https://stackoverflow.com/questions/38647716/error-in-reading-html-to-data-frame-in-python-module-object-has-no-attribute

`pip install --upgrade html5lib==1.0b8`

resolve it.
