### ISSUE TITLE
No module named config in ubuntu

### ISSUE THREAD

**Issue by koki1010** [P0cL4bs/WiFi-Pumpkin-deprecated#21]
WARNING: No route found for IPv6 destination :: (no default route?)
Traceback (most recent call last):
File "/usr/share/WiFi-Pumpkin/wifi-pumpkin.py", line 5, in
from Core.Main import Initialize
File "/usr/share/WiFi-Pumpkin/Core/Main.py", line 16, in
from Core.helpers.update import frm_githubUpdate
File "/usr/share/WiFi-Pumpkin/Core/helpers/update.py", line 4, in
from Core.loaders.master.github import GithubUpdate,UrllibDownload
File "/usr/share/WiFi-Pumpkin/Core/loaders/master/github.py", line 1, in
from config import Config
ImportError: No module named config

**Comment by mh4x0f** [comment]
https://github.com/P0cL4bs/WiFi-Pumpkin/wiki/Installation#to-install-another-linux-distro
