### ISSUE TITLE
OSError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by iosdec** [P0cL4bs/WiFi-Pumpkin-deprecated#219]
I'm using Kali Linux and the GUI works perfect - apart from when I go to click "Start", no WiFi network is created and I get this in the terminal:

[*] Loading debugging mode
[*] Current Session::ID [MjQxMTE=]
[*] enable forwarding in iptables
Traceback (most recent call last):
   File "/usr/share/WiFi-Pumpkin/core/main.py", line 1362, in Start_PumpAP
      self.CoreSettings()
   File "/usr/lib/python2.7/subprocess.py", line 1199, in CoreSettings
      for i in self.SettingsAP['kill']: Popen(i.split(), stdout=PIPE,shell=False,stderr=PIPE)
   File "/usr/lib/python2.7/subprocess.py", line 1024, in _execute_child
      raise child_exception
OSError: [Errno 2] No such file or directory

**Comment by mh4x0f** [comment]
Same issue here  #217
