### ISSUE TITLE
ImportError: No module named bs4

### ISSUE THREAD

**Issue by gwa99a9** [P0cL4bs/WiFi-Pumpkin-deprecated#226]
## What's the problem (or question)?

instafreak@0-LOCAL:~/WiFi-Pumpkin$ sudo wifi-pumpkin
Traceback (most recent call last):
  File "wifi-pumpkin.py", line 39, in <module>
    from core.loaders.checker.networkmanager import CLI_NetworkManager,UI_NetworkManager
  File "/usr/share/WiFi-Pumpkin/core/loaders/checker/networkmanager.py", line 4, in <module>
    from core.main import Initialize
  File "/usr/share/WiFi-Pumpkin/core/main.py", line 32, in <module>
    from core.widgets.tabmodels import (
  File "/usr/share/WiFi-Pumpkin/core/widgets/tabmodels.py", line 7, in <module>
    from core.utility.threads import ThreadPopen
  File "/usr/share/WiFi-Pumpkin/core/utility/threads.py", line 19, in <module>
    from core.servers.proxy.http.controller.handler import MasterHandler
  File "/usr/share/WiFi-Pumpkin/core/servers/proxy/http/controller/handler.py", line 1, in <module>
    from plugins.extension import *
  File "/usr/share/WiFi-Pumpkin/plugins/extension/beef.py", line 1, in <module>
    from bs4 import BeautifulSoup
ImportError: No module named bs4

#### Please tell us details about your environment.
* Card wireless adapters name (please check if support AP/mode): 
* Version used tool: latest
* Virtual Machine (yes or no and which):  No
* Operating System and version: Ubuntu 17.4

**Comment by mh4x0f** [comment]
``` sh
$ sudo pip install bs4
```
