### ISSUE TITLE
Error bs4 python module 

### ISSUE THREAD

**Issue by carlocrasti** [P0cL4bs/WiFi-Pumpkin-deprecated#228]
Hello, this is error:

~# wifi-pumpkin
Traceback (most recent call last):
  File "wifi-pumpkin.py", line 39, in <module>
    from core.loaders.checker.networkmanager import CLI_NetworkManager,UI_NetworkManager
  File "/usr/share/WiFi-Pumpkin/core/loaders/checker/networkmanager.py", line 4, in <module>
    from core.main import Initialize
  File "/usr/share/WiFi-Pumpkin/core/main.py", line 32, in <module>
    from core.widgets.tabmodels import (
  File "/usr/share/WiFi-Pumpkin/core/widgets/tabmodels.py", line 7, in <module>
    from core.utility.threads import ThreadPopen
  File "/usr/share/WiFi-Pumpkin/core/utility/threads.py", line 19, in <module>
    from core.servers.proxy.http.controller.handler import MasterHandler
  File "/usr/share/WiFi-Pumpkin/core/servers/proxy/http/controller/handler.py", line 1, in <module>
    from plugins.extension import *
  File "/usr/share/WiFi-Pumpkin/plugins/extension/html_inject.py", line 2, in <module>
    from bs4 import BeautifulSoup
  File "build/bdist.linux-x86_64/egg/bs4/__init__.py", line 30, in <module>
  File "build/bdist.linux-x86_64/egg/bs4/builder/__init__.py", line 314, in <module>
  File "build/bdist.linux-x86_64/egg/bs4/builder/_html5lib.py", line 70, in <module>
AttributeError: 'module' object has no attribute '_base'

I have update html5lib.py but the error is the same.
Please help me
Thanks

Network adapter TpLink wn722n
no vmachine
Kali linux rolling
wifi pumpkin latest version

**Comment by carlocrasti** [comment]
Thank you very much
