### ISSUE TITLE
please help

### ISSUE THREAD

**Issue by eisyeisy** [P0cL4bs/WiFi-Pumpkin-deprecated#233]
## What's the problem (or question)?
Please help me!
After the installation, if I start WIfi-Pumpkin, Kali Linux show me the following Text:

Traceback (most recent call last):
  File "wifi-pumpkin.py", line 39, in <module>
    from core.loaders.checker.networkmanager import CLI_NetworkManager,UI_NetworkManager
  File "/usr/share/WiFi-Pumpkin/core/loaders/checker/networkmanager.py", line 3, in <module>
    from core.utils import Refactor
  File "/usr/share/WiFi-Pumpkin/core/utils.py", line 9, in <module>
    from scapy.all import *
  File "/usr/lib/python2.7/dist-packages/scapy/all.py", line 28, in <module>
    from scapy.route6 import *
  File "/usr/lib/python2.7/dist-packages/scapy/route6.py", line 273, in <module>
    conf.route6 = Route6()
  File "/usr/lib/python2.7/dist-packages/scapy/route6.py", line 31, in __init__
    self.resync()
  File "/usr/lib/python2.7/dist-packages/scapy/route6.py", line 44, in resync
    self.routes = read_routes6()
  File "/usr/lib/python2.7/dist-packages/scapy/arch/linux.py", line 283, in read_routes6
    cset = scapy.utils6.construct_source_candidate_set(d, dp, devaddrs, LOOPBACK_NAME)
  File "/usr/lib/python2.7/dist-packages/scapy/utils6.py", line 50, in construct_source_candidate_set
    if in6_isgladdr(addr) or in6_isuladdr(addr):
  File "/usr/lib/python2.7/dist-packages/scapy/utils6.py", line 708, in in6_isgladdr
    return in6_isincluded(str, '2000::', 3)
  File "/usr/lib/python2.7/dist-packages/scapy/utils6.py", line 651, in in6_isincluded
    temp = inet_pton(socket.AF_INET6, addr)
  File "/usr/lib/python2.7/dist-packages/scapy/pton_ntop.py", line 40, in inet_pton
    raise Exception("Illegal syntax for IP address")
Exception: Illegal syntax for IP address

What is that for a issue? And what can I do?

#### Please tell us details about your environment.
* Card wireless adapters name (please check if support AP/mode): Alfa
* Version used tool:  ?
* Virtual Machine (yes or no and which): no
* Operating System and version: Kali Linux 2017.02

**Comment by mh4x0f** [comment]
the tool doesn't have support for IPv6 computer network.
