### ISSUE TITLE
Got error when starting GUI

### ISSUE THREAD

**Issue by QuantumLiu** [P0cL4bs/WiFi-Pumpkin-deprecated#245]
## What's the problem (or question)?
run
`python wifi-pumpkin.py`
Got
```
Loading GUI...
Traceback (most recent call last):
  File "wifi-pumpkin.py", line 60, in <module>
    if networkcontrol.run():
  File "/home/quantumliu/WiFi-Pumpkin/core/loaders/checker/networkmanager.py", line 175, in run
    if not self.check_interfaceinNetWorkManager(interface):
  File "/home/quantumliu/WiFi-Pumpkin/core/loaders/checker/networkmanager.py", line 165, in check_interfaceinNetWorkManager
    if mac in open(self.mn_path,'r').read():
TypeError: 'in <string>' requires string as left operand, not NoneType

```
*answer here*
I edited the file as a workaround.
```
    def check_interfaceinNetWorkManager(self,interface):
        ''' check if interface is already in file config'''
        mac = Refactor.get_interface_mac(interface)
        mac=(mac if mac else 'error')
        if mac in open(self.mn_path,'r').read():
            return True
        if interface in open(self.mn_path,'r').read():
            return True
        return False
```
And it seems worked.

#### Please tell us details about your environment.
* Card wireless adapters name (please check if support AP/mode):
* Version used tool: python2.7(anaconda env)
* Virtual Machine (yes or no and which): 
* Operating System and version: ubuntu16

**Comment by mh4x0f** [comment]
@QuantumLiu send me a pull request with this change. thank's
