### ISSUE TITLE
Error for init wifi-pumpkin 

### ISSUE THREAD

**Issue by AlejandrinoSilva** [P0cL4bs/WiFi-Pumpkin-deprecated#254]
## What's the problem (or question)?
sudo wifi-pumpkin 
Traceback (most recent call last):
  File "wifi-pumpkin.py", line 39, in <module>
    from core.loaders.checker.networkmanager import CLI_NetworkManager,UI_NetworkManager
  File "/usr/share/WiFi-Pumpkin/core/loaders/checker/networkmanager.py", line 3, in <module>
    from core.utils import Refactor
  File "/usr/share/WiFi-Pumpkin/core/utils.py", line 9, in <module>
    from scapy.all import *
  File "/usr/lib/python2.7/dist-packages/scapy/all.py", line 16, in <module>
    from scapy.arch import *
  File "/usr/lib/python2.7/dist-packages/scapy/arch/__init__.py", line 72, in <module>
    from scapy.arch.linux import *
  File "/usr/lib/python2.7/dist-packages/scapy/arch/linux.py", line 551, in <module>
    conf.iface = get_working_if()
  File "/usr/lib/python2.7/dist-packages/scapy/arch/linux.py", line 120, in get_working_if
    ifflags = struct.unpack("16xH14x",get_if(i,SIOCGIFFLAGS))[0]
  File "/usr/lib/python2.7/dist-packages/scapy/arch/common.py", line 20, in get_if
    ifreq = ioctl(sck, cmd, struct.pack("16p16x", iff))
IOError: [Errno 19] No such device

*answer here*

#### Please tell us details about your environment.
* Card wireless adapters name (please check if support AP/mode):
* Version used tool: python2.7
* Virtual Machine (yes or no and which): No
* Operating System and version: Parrot Os

**Comment by mh4x0f** [comment]
I think that the problem come from your network. because the function get_working_if() from scapy is return the problem with interface. I recommend to try update the scapy module.
