### ISSUE TITLE
Errors at startup WiFi-Pumpkin

### ISSUE THREAD

**Issue by adolfaka** [P0cL4bs/WiFi-Pumpkin-deprecated#257]
## What's the problem (or question)?

*Running causes a lot of critical errors related to the problems of connected Python modules*

`root@kali:~# sudo wifi-pumpkin
Traceback (most recent call last):
  File "wifi-pumpkin.py", line 39, in <module>
    from core.loaders.checker.networkmanager import CLI_NetworkManager,UI_NetworkManager
  File "/usr/share/WiFi-Pumpkin/core/loaders/checker/networkmanager.py", line 4, in <module>
    from core.main import Initialize
  File "/usr/share/WiFi-Pumpkin/core/main.py", line 31, in <module>
    from core.widgets.tabmodels import (
  File "/usr/share/WiFi-Pumpkin/core/widgets/tabmodels.py", line 7, in <module>
    from core.utility.threads import ThreadPopen
  File "/usr/share/WiFi-Pumpkin/core/utility/threads.py", line 19, in <module>
    from core.servers.proxy.http.controller.handler import MasterHandler
  File "/usr/share/WiFi-Pumpkin/core/servers/proxy/http/controller/handler.py", line 4, in <module>
    from mitmproxy import controller,flow
  File "/usr/lib/python2.7/dist-packages/mitmproxy/flow/__init__.py", line 5, in <module>
    from mitmproxy.flow.master import FlowMaster
  File "/usr/lib/python2.7/dist-packages/mitmproxy/flow/master.py", line 15, in <module>
    from mitmproxy.onboarding import app
  File "/usr/lib/python2.7/dist-packages/mitmproxy/onboarding/app.py", line 10, in <module>
    from mitmproxy.proxy import config
  File "/usr/lib/python2.7/dist-packages/mitmproxy/proxy/__init__.py", line 4, in <module>
    from .root_context import RootContext
  File "/usr/lib/python2.7/dist-packages/mitmproxy/proxy/root_context.py", line 10, in <module>
    from mitmproxy import protocol
  File "/usr/lib/python2.7/dist-packages/mitmproxy/protocol/__init__.py", line 37, in <module>
    from .http2 import Http2Layer
  File "/usr/lib/python2.7/dist-packages/mitmproxy/protocol/http2.py", line 10, in <module>
    from h2 import connection
  File "/usr/local/lib/python2.7/dist-packages/h2/connection.py", line 13, in <module>
    from hyperframe.frame import (
ImportError: cannot import name ExtensionFrame`

![2017-07-26 13 03 08](https://user-images.githubusercontent.com/25989971/28613252-eda8bb6e-7202-11e7-948a-e50c762f67b0.png)

#### Please tell us details about your environment.
* Card wireless adapters name (please check if support AP/mode): Broadcom on Raspberry Pi 3B
* Version used tool: BCM43438
* Virtual Machine (yes or no and which): No
* Operating System and version: Linux kali 4.4.50-v7+ #1 SMP Sun Mar 26 01:04:50 CDT 2017 armv7l GNU/Linux from here https://build.nethunter.com/nexmon-pi-builds/kali-0.1-rpi3-nexmon.img.xz

**Comment by afkalways** [comment]
I'm having similar issues, did you ever figure out the fix to this?
