### ISSUE TITLE
Error with Windows Update

### ISSUE THREAD

**Issue by Fabrimat** [P0cL4bs/WiFi-Pumpkin-deprecated#26]
If I try to start a server with Windows Update Attack Generator I get this error in console:

`Traceback (most recent call last):
  File "/usr/share/WiFi-Pumpkin/Modules/spreads/UpdateFake.py", line 178, in server_start
    'Templates/Update/Windows_Update/','windows-update.exe',True)
  File "/usr/share/WiFi-Pumpkin/Modules/spreads/UpdateFake.py", line 166, in SettingsPage
    ip = Refactor.get_Ipaddr(self.cb_interface.currentText())
  File "/usr/share/WiFi-Pumpkin/Core/Utils.py", line 599, in get_Ipaddr
    return get_if_addr(card)
  File "/usr/lib/python2.7/dist-packages/scapy/arch/__init__.py", line 36, in get_if_addr
    return socket.inet_ntoa(get_if_raw_addr(iff))
  File "/usr/lib/python2.7/dist-packages/scapy/arch/linux.py", line 86, in get_if_raw_addr
    return get_if(iff, SIOCGIFADDR)[20:24]
  File "/usr/lib/python2.7/dist-packages/scapy/arch/linux.py", line 269, in get_if
    ifreq = ioctl(s, cmd, struct.pack("16s16x",iff))
struct.error: argument for 's' must be a string
`

**Comment by mh4x0f** [comment]
fixed,thanks for issue
