### ISSUE TITLE
 No such file or directory: 'settings/dhcpd.conf'

### ISSUE THREAD

**Issue by jinyu00** [P0cL4bs/WiFi-Pumpkin-deprecated#266]
## What's the problem (or question)?
I can't start the tool.When i click Start ,It has this error info:

```
Loading GUI...
WiFi-Pumpkin Running!

[*] Loading debugging mode
[*] Current Session::ID [MzUyODA=]
[*] Configuring hostapd...
SIOCSIFFLAGS: 由于 RF-kill 而无法操作
[*] Enable forwarding in iptables...
Traceback (most recent call last):
  File "/root/WiFi-Pumpkin/core/main.py", line 1372, in Start_PumpAP
    self.CoreSettings()
  File "/root/WiFi-Pumpkin/core/main.py", line 1213, in CoreSettings
    with open('settings/dhcpd.conf','w') as dhcp:
IOError: [Errno 2] 没有那个文件或目录: 'settings/dhcpd.conf'


```

#### Please tell us details about your environment.
* Card wireless adapters name (please check if support AP/mode):
tp-link wn822, support AP/mode

* Version used tool: 
just clone the code today and install it.

* Virtual Machine (yes or no and which): 
yes 
* Operating System and version: 
kali 2.0

**Comment by jinyu00** [comment]
the Screenshot：
![xxx](http://chuantu.biz/t5/165/1502266167x2890191637.jpg)
