### ISSUE TITLE
'module' object has no attribute '_base

### ISSUE THREAD

**Issue by genericcx** [P0cL4bs/WiFi-Pumpkin-deprecated#274]
## What's the problem (or question)?

Since a recent `git pull` the following traceback is seen when starting

```
[=] checking dependencies  
----[✔]----[+] hostapd Installed
----------------------------------------
[+] Distribution Name: Kali
----------------------------------------
[=]  Install WiFi-Pumpkin 
[✔] binary::/usr/bin/
[✔] wifi-pumpkin installed with success
[✔] execute  sudo wifi-pumpkin in terminal
[+] P0cL4bs Team CopyRight 2015-2017
[+] Enjoy
root@xxx:~/WiFi-Pumpkin# ./wifi-pumpkin
Traceback (most recent call last):
  File "wifi-pumpkin.py", line 40, in <module>
    from core.loaders.checker.networkmanager import CLI_NetworkManager,UI_NetworkManager
  File "/usr/share/WiFi-Pumpkin/core/loaders/checker/networkmanager.py", line 4, in <module>
    from core.main import Initialize
  File "/usr/share/WiFi-Pumpkin/core/main.py", line 32, in <module>
    from core.widgets.tabmodels import (
  File "/usr/share/WiFi-Pumpkin/core/widgets/tabmodels.py", line 7, in <module>
    from core.utility.threads import ThreadPopen
  File "/usr/share/WiFi-Pumpkin/core/utility/threads.py", line 19, in <module>
    from core.servers.proxy.http.controller.handler import MasterHandler
  File "/usr/share/WiFi-Pumpkin/core/servers/proxy/http/controller/handler.py", line 1, in <module>
    from plugins.extension import *
  File "/usr/share/WiFi-Pumpkin/plugins/extension/no_cache.py", line 2, in <module>
    from plugins.extension.plugin import PluginTemplate
  File "/usr/share/WiFi-Pumpkin/plugins/extension/plugin.py", line 2, in <module>
    from bs4 import BeautifulSoup
  File "/usr/local/lib/python2.7/dist-packages/bs4/__init__.py", line 30, in <module>
    from .builder import builder_registry, ParserRejectedMarkup
  File "/usr/local/lib/python2.7/dist-packages/bs4/builder/__init__.py", line 314, in <module>
    from . import _html5lib
  File "/usr/local/lib/python2.7/dist-packages/bs4/builder/_html5lib.py", line 70, in <module>
    class TreeBuilderForHtml5lib(html5lib.treebuilders._base.TreeBuilder):
AttributeError: 'module' object has no attribute '_base'
```
Fixed with 
`pip install --upgrade beautifulsoup4`

#### Please tell us details about your environment.
* Card wireless adapters name (please check if support AP/mode):
* Version used tool: 
```
~/WiFi-Pumpkin# git pull
Already up-to-date.
```
* Virtual Machine (yes or no and which): 
No
* Operating System and version: 
Kali

**Comment by mh4x0f** [comment]
just try upgrade the beautifulsoup4 and html5lib and it resolved the issue:
``` sh
pip install --upgrade beautifulsoup4
pip install --upgrade html5lib
```
