### ISSUE TITLE
subprocess.call() not working as expected

### ISSUE THREAD

**Issue by oliverhavrila** [P0cL4bs/WiFi-Pumpkin-deprecated#279]
Hello guys,

I hope you can help me.
I am using Kali linux 2017.1 on Raspberry Pi 2 and wireless card is: TP-LINK TL-WN722N
And this is error when i try to start it

[*] Loading debugging mode
[*] Current Session::ID [ODg2Mjk=]
[*] Configuring hostapd...
[*] Enable forwarding in iptables...
Traceback (most recent call last):
File "/usr/share/WiFi-Pumpkin/core/main.py", line 1312, in Start_PumpAP self.CoreSettings()
File "/usr/share/WiFi-Pumpkin/core/main.py", line 1166, in CoreSettings for line in self.SettingsAP['kill']: Popen(split(line), stdout=PIPE,shell=False,stderr=PIPE)
File "/usr/lib/python2.7/subprocess.py", line 390, in __init__errread, errwrite)
File "/usr/lib/python2.7/subprocess.py", line 1024, in _execute_child raise child_exception
OSError: [Errno 2] No such file or directory

Thanks a lot

**Comment by oliverhavrila** [comment]
I send you output from the command bellow

list | grep "Supported interface modes" -A 10
        Supported interface modes:
                 * IBSS
                 * managed
                 * AP
                 * AP/VLAN
                 * monitor
                 * mesh point
                 * P2P-client
                 * P2P-GO
                 * outside context of a BSS
        Band 1:
