### ISSUE TITLE
NameError: name 'pyqtSlot' is not defined

### ISSUE THREAD

**Issue by adolfaka** [P0cL4bs/WiFi-Pumpkin-deprecated#287]
## What's the problem (or question)?

*root@kali:~/WiFi-Pumpkin# sudo wifi-pumpkin
Traceback (most recent call last):
  File "wifi-pumpkin.py", line 37, in <module>
    from core.loaders.checker.networkmanager import CLI_NetworkManager,UI_NetworkManager
  File "/usr/share/WiFi-Pumpkin/core/loaders/checker/networkmanager.py", line 3, in <module>
    from core.main import Initialize,QtGui
  File "/usr/share/WiFi-Pumpkin/core/main.py", line 28, in <module>
    from core.widgets.tabmodels import (
  File "/usr/share/WiFi-Pumpkin/core/widgets/tabmodels.py", line 10, in <module>
    from core.widgets.pluginssettings import PumpkinProxySettings
  File "/usr/share/WiFi-Pumpkin/core/widgets/pluginssettings.py", line 3, in <module>
    import modules as GUI
  File "/usr/share/WiFi-Pumpkin/modules/__init__.py", line 7, in <module>
    module = loader.find_module(name).load_module(name)
  File "/usr/lib/python2.7/pkgutil.py", line 246, in load_module
    mod = imp.load_module(fullname, self.file, self.filename, self.etc)
  File "/usr/share/WiFi-Pumpkin/modules/poisoners/__init__.py", line 7, in <module>
    module = loader.find_module(name).load_module(name)
  File "/usr/lib/python2.7/pkgutil.py", line 246, in load_module
    mod = imp.load_module(fullname, self.file, self.filename, self.etc)
  File "/usr/share/WiFi-Pumpkin/modules/poisoners/ArpPosion.py", line 31, in <module>
  File "/usr/share/WiFi-Pumpkin/modules/poisoners/ArpPosion.py", line 205, in frm_Arp_Poison
NameError: name 'pyqtSlot' is not defined*

#### Please tell us details about your environment.
* Card wireless adapters name (please check if support AP/mode): Chipset: Ralink Technology, Corp. RT2870/RT3070, Driver: rt2800usb
* Version used tool: 0.85
* Virtual Machine (yes or no and which):  no
* Operating System and version: Linux kali 4.4.50-v7+ #1 SMP Wed Aug 30 11:08:41 CDT 2017 armv7l GNU/Linux on RPi 3B

**Comment by mh4x0f** [comment]
nice issue, the python compiled code is the problem , you can solve the bug using the command bellow.
``` sh 
cd /usr/share/WiFi-Pumpkin/
sudo find . -name '*.pyc' -delete
```
