### ISSUE TITLE
HSTS problem

### ISSUE THREAD

**Issue by belini** [P0cL4bs/WiFi-Pumpkin-deprecated#31]
can't get redirected to https
got errors 

2016-03-09 11:38:43,736 : [10.0.0.21] GET www.yahoo.com/
WARNING:root:Host resolution error: [Failure instance: Traceback: <type 'exceptions.ValueError'>: I/O operation on closed file.
/usr/lib/python2.7/dist-packages/twisted/internet/defer.py:588:_runCallbacks
/usr/lib/python2.7/dist-packages/twisted/internet/base.py:254:_checkTimeout
/usr/lib/python2.7/dist-packages/twisted/internet/defer.py:393:callback
/usr/lib/python2.7/dist-packages/twisted/internet/defer.py:501:_startRunCallbacks
--- <exception caught here> ---
/usr/lib/python2.7/dist-packages/twisted/internet/defer.py:588:_runCallbacks
/usr/share/WiFi-Pumpkin/Plugins/sergio_proxy/sslstrip/ClientRequest.py:92:handleHostResolvedSuccess

next errors

2016-03-09 11:38:58,196 : [10.0.0.21] GET b.scorecardresearch.com/p2?c1=2&c2=7241469&c5=1197228339&c7=http%3A%2F%2Fwww.yahoo.com%2F&ns__t...
Unhandled Error
Traceback (most recent call last):
  File "/usr/share/WiFi-Pumpkin/Core/Main.py", line 271, in run
    reactor.run(installSignalHandlers=False)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1194, in run
    self.mainLoop()
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1206, in mainLoop
    self.doIteration(t)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/epollreactor.py", line 396, in doPoll
    log.callWithLogger(selectable, _drdw, selectable, fd, event)
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/python/log.py", line 101, in callWithLogger
    return callWithContext({"system": lp}, func, _args, *_kw)
  File "/usr/lib/python2.7/dist-packages/twisted/python/log.py", line 84, in callWithContext
    return context.call({ILogContext: newCtx}, func, _args, *_kw)
  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, _args, *_kw)
  File "/usr/lib/python2.7/dist-packages/twisted/python/context.py", line 81, in callWithContext
    return func(_args,_*kw)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/posixbase.py", line 610, in _doReadOrWrite
    self._disconnectSelectable(selectable, why, inRead)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/posixbase.py", line 255, in _disconnectSelectable
    selectable.connectionLost(f)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/tcp.py", line 479, in connectionLost
    self._commonConnection.connectionLost(self, reason)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/tcp.py", line 293, in connectionLost
    protocol.connectionLost(reason)
  File "/usr/lib/python2.7/dist-packages/twisted/web/http.py", line 477, in connectionLost
    self.handleResponseEnd()
  File "/usr/share/WiFi-Pumpkin/Plugins/sergio_proxy/sslstrip/ServerConnection.py", line 131, in handleResponseEnd
    HTTPClient.handleResponseEnd(self)
  File "/usr/lib/python2.7/dist-packages/twisted/web/http.py", line 488, in handleResponseEnd
    self.handleResponse(b)
  File "/usr/share/WiFi-Pumpkin/Plugins/sergio_proxy/sslstrip/ServerConnection.py", line 163, in handleResponse
    self.client.write(data)
  File "/usr/lib/python2.7/dist-packages/twisted/web/http.py", line 967, in write
    raise RuntimeError('Request.write called on a request after '
exceptions.RuntimeError: Request.write called on a request after Request.finish was called.

**Comment by mh4x0f** [comment]
this problem can be the plugins sslstrip, but I checked it was working correctly. try run again the access point, unable to reproduce this error.
