### ISSUE TITLE
struct.error: argument for 's' must be a string <Strikes Again>

### ISSUE THREAD

**Issue by gitxmax** [P0cL4bs/WiFi-Pumpkin-deprecated#326]
Hello,
I have a fresh install of Pumpkin.

When I launch the "ARP POISONER" module, i get this error:

Traceback (most recent call last): File "/usr/share/WiFi-Pumpkin/core/main.py", line 680, in show_arp_posion self.Farp_posion = GUIModules.frm_Arp_Poison(self.window_phishing) File "/usr/share/WiFi-Pumpkin/modules/poisoners/arp_poisoner.py", line 42, in __init__ self.GUI() File "/usr/share/WiFi-Pumpkin/modules/poisoners/arp_poisoner.py", line 145, in GUI self.ConfigureEdits() File "/usr/share/WiFi-Pumpkin/modules/poisoners/arp_poisoner.py", line 174, in ConfigureEdits self.txt_mac.setText(Refactor.getHwAddr(x['activated'][0])) File "/usr/share/WiFi-Pumpkin/core/utils.py", line 237, in getHwAddr info = ioctl(s.fileno(), 0x8927, pack('256s', ifname[:15])) struct.error: argument for 's' must be a string

Running Kali 17.1 on raspberry 3 #

**Comment by keviiin38** [comment]
I had the same problem, i think that your AP isn't started ?
Tell me if I'm wrong
I solved this error by trying when the AP was started

**Comment by mh4x0f** [comment]
@keviiin38 the arp poisoner it not necessary when AP started, I'll lock this option coming soon.
