### ISSUE TITLE
Error trying to iniciate WP

### ISSUE THREAD

**Issue by ghost** [P0cL4bs/WiFi-Pumpkin-deprecated#343]
When I try to do "sudo wifi-pumpkin"
This appears
Please help

Traceback (most recent call last):
  File "wifi-pumpkin.py", line 37, in <module>
    from core.utility.application import ApplicationLoop
  File "/usr/share/WiFi-Pumpkin/core/utility/application.py", line 3, in <module>
    from core.main import version
  File "/usr/share/WiFi-Pumpkin/core/main.py", line 24, in <module>
    from core.utils import (
  File "/usr/share/WiFi-Pumpkin/core/utils.py", line 9, in <module>
    from scapy.all import *
  File "/usr/local/lib/python2.7/dist-packages/scapy/all.py", line 10, in <module>
    from .config import *
  File "/usr/local/lib/python2.7/dist-packages/scapy/config.py", line 11, in <module>
    from .data import *
  File "/usr/local/lib/python2.7/dist-packages/scapy/data.py", line 184, in <module>
    TCP_SERVICES,UDP_SERVICES=load_services("/etc/services")
  File "/usr/local/lib/python2.7/dist-packages/scapy/data.py", line 109, in load_services
    f=open(filename, errors='ignore')
TypeError: 'errors' is an invalid keyword argument for this function

**Comment by ranafaraznaru** [comment]
> When I try to do "sudo wifi-pumpkin"
> This appears
> Please help
> 
> Traceback (most recent call last):
> File "wifi-pumpkin.py", line 37, in
> from core.utility.application import ApplicationLoop
> File "/usr/share/WiFi-Pumpkin/core/utility/application.py", line 3, in
> from core.main import version
> File "/usr/share/WiFi-Pumpkin/core/main.py", line 24, in
> from core.utils import (
> File "/usr/share/WiFi-Pumpkin/core/utils.py", line 9, in
> from scapy.all import *
> File "/usr/local/lib/python2.7/dist-packages/scapy/all.py", line 10, in
> from .config import *
> File "/usr/local/lib/python2.7/dist-packages/scapy/config.py", line 11, in
> from .data import *
> File "/usr/local/lib/python2.7/dist-packages/scapy/data.py", line 184, in
> TCP_SERVICES,UDP_SERVICES=load_services("/etc/services")
> File "/usr/local/lib/python2.7/dist-packages/scapy/data.py", line 109, in load_services
> f=open(filename, errors='ignore')
> TypeError: 'errors' is an invalid keyword argument for this function

please tell me if you have solved this issue ? i have this same issue
