### ISSUE TITLE
Deauth list not populating

### ISSUE THREAD

**Issue by mikeoxlarge** [P0cL4bs/WiFi-Pumpkin-deprecated#36]
OS 64 Bit Kali
ALFA card (atheros)

Fairly new user to this so not sure if this is a genuine issue but kinda guessing it is, when you scan networks in the deauth module nothing is returned and the following is displayed in the console window, taking a guess that "error" is a genuine error and not me doing something wrong.

Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(_self.__args, *_self.__kwargs)
  File "/root/tools/WiFi-Pumpkin/Modules/wireless/WirelessDeauth.py", line 156, in scan_diveces_airodump
    self.cap = get_network_scan()
  File "/root/tools/WiFi-Pumpkin/Core/utility/extract.py", line 52, in get_network_scan
    essid = network.find('essid').text
AttributeError: 'NoneType' object has no attribute 'text'

**Comment by mh4x0f** [comment]
You changed in Settings->Scan from Aircrack-ng ok. when you start scan networks in the deauth module you can see this window?

![](http://s32.postimg.org/myg2pa09h/snapshot189999.png)
