### ISSUE TITLE
Error when runing

### ISSUE THREAD

**Issue by mother2110** [P0cL4bs/WiFi-Pumpkin-deprecated#436]
Before opening a new issue, please read this [wiki](https://github.com/P0cL4bs/WiFi-Pumpkin/wiki/Bug-reporting)

## What's the problem (or question)?

[root:~/pentesting/wifi/WiFi-Pumpkin]# sudo wifi-pumpkin                                                                   (master✱) 
You do not have a working installation of the service_identity module: 'cannot import name opentype'.  Please install it from <https://pypi.python.org/pypi/service_identity> and make sure all of its dependencies are satisfied.  Without the service_identity module, Twisted can perform only rudimentary TLS client hostname verification.  Many valid certificate/hostname mappings may be rejected.
Traceback (most recent call last):
  File "wifi-pumpkin.py", line 36, in <module>
    from core.loaders.checker.networkmanager import CLI_NetworkManager,UI_NetworkManager
  File "/usr/share/WiFi-Pumpkin/core/loaders/checker/networkmanager.py", line 3, in <module>
    from core.main import Initialize,QtGui
  File "/usr/share/WiFi-Pumpkin/core/main.py", line 17, in <module>
    from core.utility.threads import ThreadReactor,ThreadPopen
  File "/usr/share/WiFi-Pumpkin/core/utility/threads.py", line 20, in <module>
    from core.servers.proxy.http.controller.handler import MasterHandler
  File "/usr/share/WiFi-Pumpkin/core/servers/proxy/http/controller/handler.py", line 1, in <module>
    from plugins.extension import *
  File "/usr/share/WiFi-Pumpkin/plugins/extension/shakepage.py", line 1, in <module>
    from mitmproxy.models import decoded
  File "/usr/local/lib/python2.7/dist-packages/mitmproxy/models/__init__.py", line 4, in <module>
    from .connections import ClientConnection, ServerConnection
  File "/usr/local/lib/python2.7/dist-packages/mitmproxy/models/connections.py", line 11, in <module>
    from netlib import tcp
  File "/usr/local/lib/python2.7/dist-packages/netlib/tcp.py", line 18, in <module>
    from backports import ssl_match_hostname
ImportError: cannot import name ssl_match_hostname

#### Please tell us details about your environment.
* Card wireless adapters name (please check if support AP/mode):
* Version used tool: .8.7
* Virtual Machine (yes or no and which): No
* Operating System and version:  Kali 2018.4

**Comment by mother2110** [comment]
I do have service_identity installed per the other responses.

**Comment by hdawg12** [comment]
pip install --upgrade google-auth-oauthlib  worked for me

**Comment by mother2110** [comment]
root:~/pentesting/wifi/WiFi-Pumpkin]# pip install --upgrade google-auth-oauthlib                                          (master✱) 
Requirement already up-to-date: google-auth-oauthlib in /usr/local/lib/python2.7/dist-packages
Requirement already up-to-date: requests-oauthlib>=0.7.0 in /usr/local/lib/python2.7/dist-packages (from google-auth-oauthlib)
Requirement already up-to-date: google-auth in /usr/local/lib/python2.7/dist-packages (from google-auth-oauthlib)
Collecting requests>=2.0.0 (from requests-oauthlib>=0.7.0->google-auth-oauthlib)
  Using cached https://files.pythonhosted.org/packages/7d/e3/20f3d364d6c8e5d2353c72a67778eb189176f08e873c9900e10c0287b84b/requests-2.21.0-py2.py3-none-any.whl
Requirement already up-to-date: oauthlib>=0.6.2 in /usr/local/lib/python2.7/dist-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib)
Requirement already up-to-date: pyasn1-modules>=0.2.1 in /usr/local/lib/python2.7/dist-packages (from google-auth->google-auth-oauthlib)
Requirement already up-to-date: cachetools>=2.0.0 in /usr/local/lib/python2.7/dist-packages (from google-auth->google-auth-oauthlib)
Collecting six>=1.9.0 (from google-auth->google-auth-oauthlib)
  Using cached https://files.pythonhosted.org/packages/73/fb/00a976f728d0d1fecfe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl
Requirement already up-to-date: rsa>=3.1.4 in /usr/local/lib/python2.7/dist-packages (from google-auth->google-auth-oauthlib)
Requirement already up-to-date: urllib3<1.25,>=1.21.1 in /usr/local/lib/python2.7/dist-packages (from requests>=2.0.0->requests-oauthlib>=0.7.0->google-auth-oauthlib)
Requirement already up-to-date: chardet<3.1.0,>=3.0.2 in /usr/lib/python2.7/dist-packages (from requests>=2.0.0->requests-oauthlib>=0.7.0->google-auth-oauthlib)
Requirement already up-to-date: idna<2.9,>=2.5 in /usr/local/lib/python2.7/dist-packages (from requests>=2.0.0->requests-oauthlib>=0.7.0->google-auth-oauthlib)
Requirement already up-to-date: certifi>=2017.4.17 in /usr/local/lib/python2.7/dist-packages (from requests>=2.0.0->requests-oauthlib>=0.7.0->google-auth-oauthlib)
Collecting pyasn1<0.5.0,>=0.4.1 (from pyasn1-modules>=0.2.1->google-auth->google-auth-oauthlib)
  Using cached https://files.pythonhosted.org/packages/d1/a1/7790cc85db38daa874f6a2e6308131b9953feb1367f2ae2d1123bb93a9f5/pyasn1-0.4.4-py2.py3-none-any.whl
Installing collected packages: requests, six, pyasn1
  Found existing installation: requests 2.11.1
    Uninstalling requests-2.11.1:
      Successfully uninstalled requests-2.11.1
  Found existing installation: six 1.10.0
    Uninstalling six-1.10.0:
      Successfully uninstalled six-1.10.0
  Found existing installation: pyasn1 0.1.9
    Uninstalling pyasn1-0.1.9:
      Successfully uninstalled pyasn1-0.1.9
Successfully installed pyasn1-0.4.4 requests-2.21.0 six-1.12.0


[root:~/pentesting/wifi/WiFi-Pumpkin]# sudo wifi-pumpkin                                                                   (master✱) 
Traceback (most recent call last):
  File "wifi-pumpkin.py", line 36, in <module>
    from core.loaders.checker.networkmanager import CLI_NetworkManager,UI_NetworkManager
  File "/usr/share/WiFi-Pumpkin/core/loaders/checker/networkmanager.py", line 3, in <module>
    from core.main import Initialize,QtGui
  File "/usr/share/WiFi-Pumpkin/core/main.py", line 17, in <module>
    from core.utility.threads import ThreadReactor,ThreadPopen
  File "/usr/share/WiFi-Pumpkin/core/utility/threads.py", line 20, in <module>
    from core.servers.proxy.http.controller.handler import MasterHandler
  File "/usr/share/WiFi-Pumpkin/core/servers/proxy/http/controller/handler.py", line 1, in <module>
    from plugins.extension import *
  File "/usr/share/WiFi-Pumpkin/plugins/extension/shakepage.py", line 1, in <module>
    from mitmproxy.models import decoded
  File "/usr/local/lib/python2.7/dist-packages/mitmproxy/models/__init__.py", line 4, in <module>
    from .connections import ClientConnection, ServerConnection
  File "/usr/local/lib/python2.7/dist-packages/mitmproxy/models/connections.py", line 11, in <module>
    from netlib import tcp
  File "/usr/local/lib/python2.7/dist-packages/netlib/tcp.py", line 18, in <module>
    from backports import ssl_match_hostname
ImportError: cannot import name ssl_match_hostname

**Comment by mother2110** [comment]
Why close it when it has not been resolved? I have tried everything I have read here.

**Comment by afkalways** [comment]
> Why close it when it has not been resolved? I have tried everything I have read here.

same situation

**Comment by mother2110** [comment]
Ya, I gave up for now on this. Been trying all year. There are other tools out there.

**Comment by snorx82** [comment]
similar problem ....

"Traceback (most recent call last):
  File "wifi-pumpkin.py", line 36, in <module>
    from core.loaders.checker.networkmanager import CLI_NetworkManager,UI_NetworkManager
  File "/usr/share/WiFi-Pumpkin/core/loaders/checker/networkmanager.py", line 3, in <module>
    from core.main import Initialize,QtGui
  File "/usr/share/WiFi-Pumpkin/core/main.py", line 33, in <module>
    from core.controllers.proxycontroller import *
  File "/usr/share/WiFi-Pumpkin/core/controllers/proxycontroller.py", line 4, in <module>
    from core.servers.proxy.package import *
  File "/usr/share/WiFi-Pumpkin/core/servers/proxy/package/SSLStripProxy.py", line 15, in <module>
    from core.widgets.docks.dockmonitor import (
  File "/usr/share/WiFi-Pumpkin/core/widgets/docks/dockmonitor.py", line 1, in <module>
    from plugins.extension import *
  File "/usr/share/WiFi-Pumpkin/plugins/extension/shakepage.py", line 1, in <module>
    from mitmproxy.models import decoded
ImportError: No module named mitmproxy.models"
