### ISSUE TITLE
cant run after installation

### ISSUE THREAD

**Issue by die-dimitry** [P0cL4bs/WiFi-Pumpkin-deprecated#445]
~/WiFi-Pumpkin$ wifi-pumpkin 
Traceback (most recent call last):
  File "wifi-pumpkin.py", line 36, in <module>
    from core.loaders.checker.networkmanager import CLI_NetworkManager,UI_NetworkManager
  File "/usr/share/WiFi-Pumpkin/core/loaders/checker/networkmanager.py", line 3, in <module>
    from core.main import Initialize,QtGui
  File "/usr/share/WiFi-Pumpkin/core/main.py", line 17, in <module>
    from core.utility.threads import ThreadReactor,ThreadPopen
  File "/usr/share/WiFi-Pumpkin/core/utility/threads.py", line 10, in <module>
    from twisted.internet import reactor
  File "/usr/lib/python2.7/dist-packages/twisted/internet/reactor.py", line 38, in <module>
    from twisted.internet import default
  File "/usr/lib/python2.7/dist-packages/twisted/internet/default.py", line 56, in <module>
    install = _getInstallFunction(platform)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/default.py", line 44, in _getInstallFunction
    from twisted.internet.epollreactor import install
  File "/usr/lib/python2.7/dist-packages/twisted/internet/epollreactor.py", line 24, in <module>
    from twisted.internet import posixbase
  File "/usr/lib/python2.7/dist-packages/twisted/internet/posixbase.py", line 18, in <module>
    from twisted.internet import error, udp, tcp
  File "/usr/lib/python2.7/dist-packages/twisted/internet/tcp.py", line 28, in <module>
    from twisted.internet._newtls import (
  File "/usr/lib/python2.7/dist-packages/twisted/internet/_newtls.py", line 21, in <module>
    from twisted.protocols.tls import TLSMemoryBIOFactory, TLSMemoryBIOProtocol
  File "/usr/lib/python2.7/dist-packages/twisted/protocols/tls.py", line 63, in <module>
    from twisted.internet._sslverify import _setAcceptableProtocols
  File "/usr/lib/python2.7/dist-packages/twisted/internet/_sslverify.py", line 157, in <module>
    verifyHostname, VerificationError = _selectVerifyImplementation()
  File "/usr/lib/python2.7/dist-packages/twisted/internet/_sslverify.py", line 140, in _selectVerifyImplementation
    from service_identity import VerificationError
  File "/home/suhail/.local/lib/python2.7/site-packages/service_identity/__init__.py", line 7, in <module>
    from . import cryptography, pyopenssl
  File "/home/suhail/.local/lib/python2.7/site-packages/service_identity/pyopenssl.py", line 14, in <module>
    from pyasn1_modules.rfc2459 import GeneralNames
  File "/home/suhail/.local/lib/python2.7/site-packages/pyasn1_modules/rfc2459.py", line 1010, in <module>
    class AttributeTypeAndValue(univ.Sequence):
  File "/home/suhail/.local/lib/python2.7/site-packages/pyasn1_modules/rfc2459.py", line 1014, in AttributeTypeAndValue
    openType=opentype.OpenType('type', certificateAttributesMap))
TypeError: __init__() got an unexpected keyword argument 'openType'

**Comment by die-dimitry** [comment]
What !  why ? why is it getting closed without the problem getting solved.
