### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by jepunband** [P0cL4bs/WiFi-Pumpkin-deprecated#489]
**Description of the bug or feature request**

**To Reproduce**
1. sudo wifi-pumpkin

**Expected behavior**
wifi-pumpkin opens up. i had no issue with the previous ver. after installing the latest ver, wifi-pumpkin shows up with these errors.

**Screenshots**
Traceback (most recent call last):
  File "wifi-pumpkin.py", line 36, in <module>
    from core.loaders.checker.networkmanager import CLI_NetworkManager,UI_NetworkManager
  File "/usr/share/WiFi-Pumpkin/core/loaders/checker/networkmanager.py", line 3, in <module>
    from core.main import Initialize,QtGui
  File "/usr/share/WiFi-Pumpkin/core/main.py", line 17, in <module>
    from core.utility.threads import ThreadReactor,ThreadPopen
  File "/usr/share/WiFi-Pumpkin/core/utility/threads.py", line 24, in <module>
    from mitmproxy import proxy, flow, options
  File "/usr/local/lib/python2.7/dist-packages/mitmproxy/flow/__init__.py", line 5, in <module>
    from mitmproxy.flow.master import FlowMaster
  File "/usr/local/lib/python2.7/dist-packages/mitmproxy/flow/master.py", line 15, in <module>
    from mitmproxy.onboarding import app
  File "/usr/local/lib/python2.7/dist-packages/mitmproxy/onboarding/app.py", line 6, in <module>
    import tornado.web
  File "/usr/local/lib/python2.7/dist-packages/tornado/web.py", line 84, in <module>
    from tornado import gen
  File "/usr/local/lib/python2.7/dist-packages/tornado/gen.py", line 1243, in <module>
    import tornado.platform.asyncio
  File "/usr/local/lib/python2.7/dist-packages/tornado/platform/asyncio.py", line 33, in <module>
    import asyncio # type: ignore
  File "/usr/local/lib/python2.7/dist-packages/asyncio/__init__.py", line 9, in <module>
    from . import selectors
  File "/usr/local/lib/python2.7/dist-packages/asyncio/selectors.py", line 39
    "{!r}".format(fileobj)) from None
                               ^
SyntaxError: invalid syntax

**Desktop (please complete the following information):**
* Version used tool: 0.8.8
* Virtual Machine (yes or no and which): no
* Operating System and version: parrot

** INCOMPLETE REPORT WILL BE CLOSED **

**Comment by mh4x0f** [comment]
this use this version the tornado module:

> sudo pip install tornado==4.4.3
