### ISSUE TITLE
Captive portal socket in use error

### ISSUE THREAD

**Issue by reaperNorman** [P0cL4bs/WiFi-Pumpkin-deprecated#523]
Trying to run WiFi Pumpkin with captive portal plugin and none of the templates can execute because of a python error in sockets.py stating the the socket it already in use.

1.Start with captive portal plugin
2. Go to Monitor tab
3. Look at error messages

Error Message for all templates:
    run_simple(host, port, self, **options)
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 1010, in run_simple
    inner()
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 963, in inner
    fd=fd,
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 821, in make_server
    host, port, app, request_handler, passthrough_errors, ssl_context, fd=fd
  File "/usr/local/lib/python2.7/dist-packages/werkzeug/serving.py", line 699, in __init__
    HTTPServer.__init__(self, server_address, handler)
  File "/usr/lib/python2.7/SocketServer.py", line 417, in __init__
    self.server_bind()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 108, in server_bind
    SocketServer.TCPServer.server_bind(self)
  File "/usr/lib/python2.7/SocketServer.py", line 431, in server_bind
    self.socket.bind(self.server_address)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 98] Address already in use

**Comment by SgtFoose** [comment]
I have the same issue:

root@Anonymo:~/WiFi-Pumpkin# wifi-pumpkin
Loading GUI...
WiFi-Pumpkin Running!
[*] Configuring Static AP Mode...
[*] Enable forwarding in iptables...
-------------------------------
AP::[PumpAP] Running...
AP::BSSID::[bc:77:37:2a:be:21] CH 11

[*] Loading debugging mode
[*] Current Session::ID [NDY0NDk=]
Traceback (most recent call last):
  File "/usr/share/WiFi-Pumpkin/core/main.py", line 819, in start_access_point
    self.dhcpcontrol.Start()
  File "/usr/share/WiFi-Pumpkin/core/controllers/dhcpcontroller.py", line 14, in Start
    self.Active.Start()
  File "/usr/share/WiFi-Pumpkin/core/servers/dhcp/dhcp.py", line 46, in Start
    self.boot()
  File "/usr/share/WiFi-Pumpkin/core/servers/dhcp/PyDHCP.py", line 23, in boot
    self.reactor = DHCPServer(str(self.parent.SessionConfig.Wireless.WLANCard.currentText()), self.parent.SessionConfig.DHCP.conf)
  File "/usr/share/WiFi-Pumpkin/core/servers/dhcp/dhcpserver.py", line 233, in __init__
    self.sock.bind(('', self.port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 98] Address already in use
