### ISSUE TITLE
tried different methods to install netfilterqueue but everything fails

### ISSUE THREAD

**Issue by sudo-techy** [P0cL4bs/WiFi-Pumpkin-deprecated#528]
root@Kali:~/WiFi-Pumpkin# wifi-pumpkin
:0: UserWarning: You do not have a working installation of the service_identity module: 'cannot import name opentype'.  Please install it from <https://pypi.python.org/pypi/service_identity> and make sure all of its dependencies are satisfied.  Without the service_identity module, Twisted can perform only rudimentary TLS client hostname verification.  Many valid certificate/hostname mappings may be rejected.
Traceback (most recent call last):
  File "wifi-pumpkin.py", line 36, in <module>
    from core.loaders.checker.networkmanager import CLI_NetworkManager,UI_NetworkManager
  File "/usr/share/WiFi-Pumpkin/core/loaders/checker/networkmanager.py", line 3, in <module>
    from core.main import Initialize,QtGui
  File "/usr/share/WiFi-Pumpkin/core/main.py", line 26, in <module>
    from netfilterqueue import NetfilterQueue
ImportError: No module named netfilterqueue

**Comment by zaijianbch** [comment]
I use VM kali2019.
I failed when I pip install -r requirements.txt.
I have a "Failed building wheel for NetfilterQueue" error.
Then I find a solution, "apt-get install build-essential python-dev libnetfilter-queue-dev".
But My wireless network card is wdn6200. Its linux driver doesn't support monitor mode, so I can't build a phishing AP......So sad...
