### ISSUE TITLE
soupsieve 

### ISSUE THREAD

**Issue by Jaguar7thNova** [P0cL4bs/WiFi-Pumpkin-deprecated#551]
**Description of the bug or feature request**
no matter what command i use, no matter how i install this, no matter what i do i get a continuous circle of errors. this one is soupsieve and pyqtSlot
pip install beautifulsoup4 --force --upgrade
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Collecting beautifulsoup4
  Using cached beautifulsoup4-4.8.2-py2-none-any.whl (106 kB)
Collecting soupsieve>=1.2
  Using cached soupsieve-1.9.5-py2.py3-none-any.whl (33 kB)
Collecting backports.functools-lru-cache; python_version < "3"
  Using cached backports.functools_lru_cache-1.6.1-py2.py3-none-any.whl (5.7 kB)
Installing collected packages: backports.functools-lru-cache, soupsieve, beautifulsoup4
  Attempting uninstall: backports.functools-lru-cache
    Found existing installation: backports.functools-lru-cache 1.6.1
    Uninstalling backports.functools-lru-cache-1.6.1:
      Successfully uninstalled backports.functools-lru-cache-1.6.1
  Attempting uninstall: soupsieve
    Found existing installation: soupsieve 1.9.5
    Uninstalling soupsieve-1.9.5:
      Successfully uninstalled soupsieve-1.9.5
  Attempting uninstall: beautifulsoup4
    Found existing installation: beautifulsoup4 4.8.2
    Uninstalling beautifulsoup4-4.8.2:
      Successfully uninstalled beautifulsoup4-4.8.2
Successfully installed backports.functools-lru-cache-1.6.1 beautifulsoup4-4.8.2 soupsieve-1.9.5
root@Ifrit:~/Desktop/WiFi-Pumpkin# wifi-pumpkin
The soupsieve package is not installed. CSS selectors cannot be used.
You are using a very old release of Beautiful Soup, last updated in 2011. If you installed the 'beautifulsoup' package through pip, you should know the 'beautifulsoup' package name is about to be reclaimed by a more recent version of Beautiful Soup which is incompatible with this version.

This will happen at some point after January 1, 2021.

If you just started this project, this is easy to fix. Install the 'beautifulsoup4' package instead of 'beautifulsoup' and start using Beautiful Soup 4.

If this is an existing project that depends on Beautiful Soup 3, the project maintainer (potentially you) needs to start the process of migrating to Beautiful Soup 4. This should be a relatively easy part of the Python 3 migration.

Traceback (most recent call last):
  File "wifi-pumpkin.py", line 36, in <module>
    from core.loaders.checker.networkmanager import CLI_NetworkManager,UI_NetworkManager
  File "/usr/share/WiFi-Pumpkin/core/loaders/checker/networkmanager.py", line 3, in <module>
    from core.main import Initialize,QtGui
  File "/usr/share/WiFi-Pumpkin/core/main.py", line 18, in <module>
    import modules as GUIModules
  File "/usr/share/WiFi-Pumpkin/modules/__init__.py", line 7, in <module>
    module = loader.find_module(name).load_module(name)
  File "/usr/lib/python2.7/pkgutil.py", line 243, in load_module
    mod = imp.load_module(fullname, self.file, self.filename, self.etc)
  File "/usr/share/WiFi-Pumpkin/modules/poisoners/__init__.py", line 7, in <module>
    module = loader.find_module(name).load_module(name)
  File "/usr/lib/python2.7/pkgutil.py", line 243, in load_module
    mod = imp.load_module(fullname, self.file, self.filename, self.etc)
  File "/usr/share/WiFi-Pumpkin/modules/poisoners/ArpPosion.py", line 31, in <module>
    class frm_Arp_Poison(PumpkinModule):
  File "/usr/share/WiFi-Pumpkin/modules/poisoners/ArpPosion.py", line 205, in frm_Arp_Poison
    @pyqtSlot(QModelIndex)
NameError: name 'pyqtSlot' is not defined

**To Reproduce**
attempt to upgrade from 0.8.5 or just try to fresh install wifi-pumpkin
**Expected behavior**
the program to work, been fighting with it for 3 days. 

**Screenshots**

**Desktop (please complete the following information):**
* Version used tool: v0.8.8
* Virtual Machine (yes or no and which): no
* Operating System and version: kali-linux-rolling up to date. 

** INCOMPLETE REPORT WILL BE CLOSED **

**Comment by Jaguar7thNova** [comment]
root@Ifrit:~/Desktop/WiFi-Pumpkin# pip install -r requirements.txt
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Requirement already satisfied: Twisted in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 1)) (19.10.0)
Requirement already satisfied: scapy in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 2)) (2.4.3)
Requirement already satisfied: bs4 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 3)) (0.0.1)
Requirement already satisfied: netaddr in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 4)) (0.7.19)
Requirement already satisfied: config in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 5)) (0.4.2)
Requirement already satisfied: dnspython in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 6)) (1.16.0)
Requirement already satisfied: isc_dhcp_leases in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 7)) (0.9.1)
Requirement already satisfied: netifaces in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 8)) (0.10.9)
Requirement already satisfied: pcapy in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 9)) (0.11.4)
Requirement already satisfied: configparser==3.3.0r1 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 10)) (3.3.0.post1)
Requirement already satisfied: NetfilterQueue in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 11)) (0.8.1)
Requirement already satisfied: configobj in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 12)) (5.0.6)
Requirement already satisfied: libarchive-c==2.1 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 13)) (2.1)
Requirement already satisfied: python-magic==0.4.6 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 14)) (0.4.6)
Requirement already satisfied: pefile in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 15)) (2019.4.18)
Requirement already satisfied: capstone in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 16)) (4.0.1)
Requirement already satisfied: hyperframe in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 17)) (5.2.0)
Requirement already satisfied: h2 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 18)) (3.2.0)
Requirement already satisfied: scapy_http in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 19)) (1.8.2)
Requirement already satisfied: service_identity in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 20)) (18.1.0)
Requirement already satisfied: backports.ssl_match_hostname in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 21)) (3.7.0.1)
Requirement already satisfied: pyOpenSSL in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 22)) (19.1.0)
Requirement already satisfied: Flask==0.11.1 in /usr/local/lib/python2.7/dist-packages (from -r requirements.txt (line 23)) (0.11.1)
Requirement already satisfied: Automat>=0.3.0 in /usr/local/lib/python2.7/dist-packages (from Twisted->-r requirements.txt (line 1)) (20.2.0)
Requirement already satisfied: hyperlink>=17.1.1 in /usr/local/lib/python2.7/dist-packages (from Twisted->-r requirements.txt (line 1)) (19.0.0)
Requirement already satisfied: PyHamcrest>=1.9.0 in /usr/local/lib/python2.7/dist-packages (from Twisted->-r requirements.txt (line 1)) (1.10.1)
Requirement already satisfied: attrs>=17.4.0 in /usr/local/lib/python2.7/dist-packages (from Twisted->-r requirements.txt (line 1)) (19.3.0)
Requirement already satisfied: incremental>=16.10.1 in /usr/local/lib/python2.7/dist-packages (from Twisted->-r requirements.txt (line 1)) (17.5.0)
Requirement already satisfied: zope.interface>=4.4.2 in /usr/local/lib/python2.7/dist-packages (from Twisted->-r requirements.txt (line 1)) (4.7.1)
Requirement already satisfied: constantly>=15.1 in /usr/local/lib/python2.7/dist-packages (from Twisted->-r requirements.txt (line 1)) (15.1.0)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python2.7/dist-packages (from bs4->-r requirements.txt (line 3)) (4.8.2)
Requirement already satisfied: six in /usr/local/lib/python2.7/dist-packages (from isc_dhcp_leases->-r requirements.txt (line 7)) (1.14.0)
Requirement already satisfied: future in /usr/local/lib/python2.7/dist-packages (from pefile->-r requirements.txt (line 15)) (0.18.2)
Requirement already satisfied: hpack<4,>=3.0 in /usr/local/lib/python2.7/dist-packages (from h2->-r requirements.txt (line 18)) (3.0.0)
Requirement already satisfied: enum34<2,>=1.1.6; python_version == "2.7" in /usr/local/lib/python2.7/dist-packages (from h2->-r requirements.txt (line 18)) (1.1.9)
Requirement already satisfied: cryptography in /usr/local/lib/python2.7/dist-packages (from service_identity->-r requirements.txt (line 20)) (2.8)
Requirement already satisfied: ipaddress; python_version < "3.3" in /usr/local/lib/python2.7/dist-packages (from service_identity->-r requirements.txt (line 20)) (1.0.23)
Requirement already satisfied: pyasn1 in /usr/local/lib/python2.7/dist-packages (from service_identity->-r requirements.txt (line 20)) (0.4.8)
Requirement already satisfied: pyasn1-modules in /usr/local/lib/python2.7/dist-packages (from service_identity->-r requirements.txt (line 20)) (0.2.8)
Requirement already satisfied: itsdangerous>=0.21 in /usr/local/lib/python2.7/dist-packages (from Flask==0.11.1->-r requirements.txt (line 23)) (1.1.0)
Requirement already satisfied: click>=2.0 in /usr/local/lib/python2.7/dist-packages (from Flask==0.11.1->-r requirements.txt (line 23)) (7.0)
Requirement already satisfied: Jinja2>=2.4 in /usr/local/lib/python2.7/dist-packages (from Flask==0.11.1->-r requirements.txt (line 23)) (2.11.1)
Requirement already satisfied: Werkzeug>=0.7 in /usr/local/lib/python2.7/dist-packages (from Flask==0.11.1->-r requirements.txt (line 23)) (1.0.0)
Requirement already satisfied: idna>=2.5 in /usr/local/lib/python2.7/dist-packages (from hyperlink>=17.1.1->Twisted->-r requirements.txt (line 1)) (2.9)
Requirement already satisfied: setuptools in /usr/local/lib/python2.7/dist-packages (from zope.interface>=4.4.2->Twisted->-r requirements.txt (line 1)) (44.0.0)
Requirement already satisfied: soupsieve>=1.2 in /usr/local/lib/python2.7/dist-packages (from beautifulsoup4->bs4->-r requirements.txt (line 3)) (1.9.5)
Requirement already satisfied: cffi!=1.11.3,>=1.8 in /usr/local/lib/python2.7/dist-packages (from cryptography->service_identity->-r requirements.txt (line 20)) (1.14.0)
Requirement already satisfied: MarkupSafe>=0.23 in /usr/local/lib/python2.7/dist-packages (from Jinja2>=2.4->Flask==0.11.1->-r requirements.txt (line 23)) (1.1.1)
Requirement already satisfied: backports.functools-lru-cache; python_version < "3" in /usr/local/lib/python2.7/dist-packages (from soupsieve>=1.2->beautifulsoup4->bs4->-r requirements.txt (line 3)) (1.6.1)
Requirement already satisfied: pycparser in /usr/local/lib/python2.7/dist-packages (from cffi!=1.11.3,>=1.8->cryptography->service_identity->-r requirements.txt (line 20)) (2.19)
root@Ifrit:~/Desktop/WiFi-Pumpkin# 
if all requirements are satisfied why will it still not run

**Comment by Jaguar7thNova** [comment]
The soupsieve package is not installed. CSS selectors cannot be used.
Loading GUI...
this is the only error left now. soupsieve has to do with python CSS selectors...hmm

pip install CSS selectors
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Collecting CSS
  Downloading css-0.1.tar.gz (1.8 kB)
Collecting selectors
  Downloading selectors-0.0.14.tar.gz (3.7 kB)
Collecting weblib
  Downloading weblib-0.1.30.tar.gz (30 kB)
Requirement already satisfied: six in /usr/local/lib/python2.7/dist-packages (from selectors) (1.14.0)
Requirement already satisfied: lxml in /usr/local/lib/python2.7/dist-packages (from selectors) (3.6.0)
Collecting pytils
  Downloading pytils-0.3.tar.gz (89 kB)
     |████████████████████████████████| 89 kB 473 kB/s 
Collecting user_agent
  Downloading user_agent-0.1.9.tar.gz (20 kB)
Building wheels for collected packages: CSS, selectors, weblib, pytils, user-agent
  Building wheel for CSS (setup.py) ... done
  Created wheel for CSS: filename=css-0.1-py2-none-any.whl size=2309 sha256=77f457d101a24bfa3e25d6f95c3661ef4a9df1a9be6d0e478c82a7c21f198139
  Stored in directory: /root/.cache/pip/wheels/3d/77/4f/4ad8eb65216d88ccc90dec75c172678847d6b9e6bb7d51c301
  Building wheel for selectors (setup.py) ... done
  Created wheel for selectors: filename=selectors-0.0.14-py2-none-any.whl size=4465 sha256=87c8963840d134237fc3c45d3e04d2837fcfed56e1b464afa8a14aff83536e1e
  Stored in directory: /root/.cache/pip/wheels/16/dd/76/0e5f5e2351049a3fc22336630a09a37cb2b39adfd7e26a6a40
  Building wheel for weblib (setup.py) ... done
  Created wheel for weblib: filename=weblib-0.1.30-py2-none-any.whl size=40155 sha256=dd24b3fe62297a21d462626f60bd0eaf88777e79771b151faf8393cb4a028f7b
  Stored in directory: /root/.cache/pip/wheels/23/14/c8/3a07d5081237ac96f63aa62fdf27b5d5116fadd54dd12334ca
  Building wheel for pytils (setup.py) ... done
  Created wheel for pytils: filename=pytils-0.3-py2-none-any.whl size=40354 sha256=63b8516822d91422ca564f54c3d7c44075719b284b75c57db8c3bdddeceabb80
  Stored in directory: /root/.cache/pip/wheels/b3/62/11/fa031453d051a69d742f1895e7b76027bc6f7d27f7d5247344
  Building wheel for user-agent (setup.py) ... done
  Created wheel for user-agent: filename=user_agent-0.1.9-py2-none-any.whl size=18808 sha256=72d52ef07d82ed91c870a9658d6daaefba80e320a73b51f7fc748e4d41d0ad61
  Stored in directory: /root/.cache/pip/wheels/80/f2/c8/a8774eea6f04a748bf24d18ef2f13a38c1aab7f3474295ea36
Successfully built CSS selectors weblib pytils user-agent
Installing collected packages: CSS, pytils, user-agent, weblib, selectors
Successfully installed CSS-0.1 pytils-0.3 selectors-0.0.14 user-agent-0.1.9 weblib-0.1.30

python2 wifi-pumpkin.py
The soupsieve package is not installed. CSS selectors cannot be used.
Loading GUI...
WiFi-Pumpkin Running!
root@Ifrit:~/Desktop/WiFi-Pumpkin#

**Comment by Jaguar7thNova** [comment]
okay so a note on my trouble shooting 
soupsieve should be recognized along with beautifulsoup4

pip install beautifulsoup4
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python2.7/dist-packages (4.8.2)
Requirement already satisfied: soupsieve>=1.2 in /usr/local/lib/python2.7/dist-packages (from beautifulsoup4) (1.9.5)
Requirement already satisfied: backports.functools-lru-cache; python_version < "3" in /usr/local/lib/python2.7/dist-packages (from soupsieve>=1.2->beautifulsoup4) (1.6.1)

pip install soupsieve 
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Requirement already satisfied: soupsieve in /usr/local/lib/python2.7/dist-packages (1.9.5)
Requirement already satisfied: backports.functools-lru-cache; python_version < "3" in /usr/local/lib/python2.7/dist-packages (from soupsieve) (1.6.1)
root@Ifrit:~/Desktop/WiFi-Pumpkin# 

python states the requirement is already satisfied and so does Wifi-pumpkin. however im thinking that wifi-pumpkin isn't detecting or doesn't know the file path to beautifulsoup4 or its soupsieve directory. How do i point wifi-pumpkin to those directories?
