### ISSUE TITLE
"/usr/lib/python2.7/dist-packages/twisted/web/http.py", line 962 : RuntimeError

### ISSUE THREAD

**Issue by the-maux** [P0cL4bs/WiFi-Pumpkin-deprecated#57]
hi, 
Just reporting an error i got.

Unhandled Error
Traceback (most recent call last):
  File "/root/Travaille/WiFi-Pumpkin/Core/utility/threads.py", line 326, in run
    reactor.run(installSignalHandlers=False)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1192, in run
    self.mainLoop()
  File "/usr/lib/python2.7/dist-packages/twisted/internet/base.py", line 1204, in mainLoop
    self.doIteration(t)
  File "/usr/lib/python2.7/dist-packages/twisted/internet/epollreactor.py", line 396, in doPoll
    log.callWithLogger(selectable, _drdw, selectable, fd, event)
--- <exception caught here> ---
  File "/usr/lib/python2.7/dist-packages/twisted/python/log.py", line 88, in callWithLogger
    return callWithContext({"system": lp}, func, _args, *_kw)

...

  File "/usr/lib/python2.7/dist-packages/twisted/web/http.py", line 474, in connectionLost
    self.handleResponseEnd()
  File "/root/Travaille/WiFi-Pumpkin/Plugins/sergio_proxy/sslstrip/ServerConnection.py", line 131, in handleResponseEnd
    HTTPClient.handleResponseEnd(self)
  File "/usr/lib/python2.7/dist-packages/twisted/web/http.py", line 485, in handleResponseEnd
    self.handleResponse(b)
  File "/root/Travaille/WiFi-Pumpkin/Plugins/sergio_proxy/sslstrip/ServerConnection.py", line 163, in handleResponse
    self.client.write(data)
  File "/usr/lib/python2.7/dist-packages/twisted/web/http.py", line 962, in write
    raise RuntimeError('Request.write called on a request after '
exceptions.RuntimeError: Request.write called on a request after Request.finish was called.

Its not aborting anything and it's not on your project, but you can handle it if you want.

**Comment by mh4x0f** [comment]
It is normal error the sslstrip when trying to bypass HSTS.They don't indicate a problem, and can be safely ignored.
