### ISSUE TITLE
exception thrown

### ISSUE THREAD

**Issue by ksesalebangim** [P0cL4bs/WiFi-Pumpkin-deprecated#61]
this exception is thrown when running on kali linux, with no injection.

Unhandled Error
Traceback (most recent call last):
  File "/usr/share/WiFi-Pumpkin/Core/utility/threads.py", line 324, in run
    reactor.run(installSignalHandlers=False)
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 1194, in run
    self.mainLoop()
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/base.py", line 1206, in mainLoop
    self.doIteration(t)
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/epollreactor.py", line 396, in doPoll
    log.callWithLogger(selectable, _drdw, selectable, fd, event)
--- <exception caught here> ---
  File "/usr/local/lib/python2.7/dist-packages/twisted/python/log.py", line 101, in callWithLogger
    return callWithContext({"system": lp}, func, _args, *_kw)
  File "/usr/local/lib/python2.7/dist-packages/twisted/python/log.py", line 84, in callWithContext
    return context.call({ILogContext: newCtx}, func, _args, *_kw)
  File "/usr/local/lib/python2.7/dist-packages/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, _args, *_kw)
  File "/usr/local/lib/python2.7/dist-packages/twisted/python/context.py", line 81, in callWithContext
    return func(_args,_*kw)
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/posixbase.py", line 610, in _doReadOrWrite
    self._disconnectSelectable(selectable, why, inRead)
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/posixbase.py", line 255, in _disconnectSelectable
    selectable.connectionLost(f)
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/tcp.py", line 479, in connectionLost
    self._commonConnection.connectionLost(self, reason)
  File "/usr/local/lib/python2.7/dist-packages/twisted/internet/tcp.py", line 293, in connectionLost
    protocol.connectionLost(reason)
  File "/usr/local/lib/python2.7/dist-packages/twisted/web/http.py", line 486, in connectionLost
    self.handleResponseEnd()
  File "/usr/share/WiFi-Pumpkin/Plugins/sergio_proxy/sslstrip/ServerConnection.py", line 132, in handleResponseEnd
    HTTPClient.handleResponseEnd(self)
  File "/usr/local/lib/python2.7/dist-packages/twisted/web/http.py", line 497, in handleResponseEnd
    self.handleResponse(b)
  File "/usr/share/WiFi-Pumpkin/Plugins/sergio_proxy/sslstrip/ServerConnection.py", line 164, in handleResponse
    self.client.write(data)
  File "/usr/local/lib/python2.7/dist-packages/twisted/web/http.py", line 896, in write
    raise RuntimeError('Request.write called on a request after '
exceptions.RuntimeError: Request.write called on a request after Request.finish was called.

**Comment by ksesalebangim** [comment]
after the error shpwed up, i added a print line in
File
"/usr/share/WiFi-Pumpkin/Plugins/sergio_proxy/sslstrip/ServerConnection.py"
the error was there before and remained the same. i did not change anything
else. just printed what was in data to see if i can figure out this error.
can you please help me?
i can revert to the version without the print, but the error is the same.
