### ISSUE TITLE
Deauth not populating for scapy or airodump-ng

### ISSUE THREAD

**Issue by binaryc0de** [P0cL4bs/WiFi-Pumpkin-deprecated#75]
Using Kali with ALFA AWUS036NH and get nothing populated with settings to use Scapy and get the following in the terminal when choosing airodump-ng for the scan:
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(_self.__args, *_self.__kwargs)
  File "/usr/share/WiFi-Pumpkin/Modules/wireless/WirelessDeauth.py", line 153, in scan_diveces_airodump
    exit_air = airdump_start(self.interface)
  File "/usr/share/WiFi-Pumpkin/Core/utility/extract.py", line 33, in airdump_start
    process.start()
  File "/usr/share/WiFi-Pumpkin/Core/utility/threads.py", line 155, in start
    self.procThread.start(self.cmd.keys()[0],self.cmd[self.cmd.keys()[0]])
AttributeError: 'list' object has no attribute 'keys'

**Comment by mh4x0f** [comment]
@binaryc0de  thanks for issue, try now
